llm_short_name: gemma4-e2b-it
enable_thinking: false
thinking_budget: null
use_format_enforcer_first_attempt: false
use_unsloth: false
random_seed_eval: 242289593
eval_dataset_name: hotpotqa-modified
max_output_tokens: 4096
second_chance_answer_token_limit: 32
num_cpu_threads: 8
sample_size: -1
responses_per_question: 16
use_model: rl
rl_experiment_name: gemma4-e2b-it_hotpotqa-modified_higher-formatting-reward_overconfidence-1
